import user_1 from './assets/user-1.png'
import user_2 from './assets/user-2.png'
import user_3 from './assets/user-3.png'
import user_4 from './assets/user-4.png'

export const constructorsData = [
    {
      name: "Construction Service Provider 1",
      city: "Jaffna",
      desc: "Building Painter",
      exp: "I have 3 years work experience and done some courses",
      online: true,
      profile: user_1,
      email: "john@email.com",
      phone: "077383839",
    },
    {
      name: "Construction Service Provider 2",
      city: "Vavuniya",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 3",
      city: "Batticaloa",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: true,
      profile: user_3,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 4",
      city: "Kandy",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_4,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 5",
      city: "Colombo",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_1,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 6",
      city: "Anuradhapura",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 7",
      city: "Mannar",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_3,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 8",
      city: "Galle",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_4,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 9",
      city: "Badulla",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_1,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 10",
      city: "Jaffna",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 11",
      city: "Kandy",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
    profile: user_3,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 12",
      city: "Colombo",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_4,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 13",
      city: "Anuradhapura",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_1,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 14",
      city: "Badulla",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 15",
      city: "Vavuniya",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_3,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Construction Service Provider 16",
      city: "Vavuniya",
      desc: "Building Constructor",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_4,
      email: "lewis@email.com",
      phone: "0769688839",
    },
  ];
  
  export const electriciansData = [
    {
      name: "Electric Service Provider 1",
      city: "Jaffna",
      desc: "Electrician",
      exp: "I have 3 years work experience and done some courses",
      online: true,
      profile: user_1,
      email: "john@email.com",
      phone: "077383839",
    },
    {
      name: "Electric Service Provider 2",
      city: "Vavuniya",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electric Service Provider 3",
      city: "Batticaloa",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: true,
      profile: user_3,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electric Service Provider 4",
      city: "Kandy",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_4,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electric Service Provider 5",
      city: "Colombo",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_1,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electric Service Provider 6",
      city: "Anuradhapura",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },

  ];

  export const electronicPersonData = [
    {
      name: "Electronic Service Provider 1",
      city: "Jaffna",
      desc: "Electrician",
      exp: "I have 3 years work experience and done some courses",
      online: true,
      profile: user_1,
      email: "john@email.com",
      phone: "077383839",
    },
    {
      name: "ElectronicService Provider 2",
      city: "Vavuniya",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electronic Service Provider 3",
      city: "Batticaloa",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: true,
      profile: user_3,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electronic Service Provider 4",
      city: "Kandy",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_4,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electronic Service Provider 5",
      city: "Colombo",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_1,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electronic Service Provider 6",
      city: "Anuradhapura",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electronic Service Provider 7",
      city: "Mannar",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_3,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electronic Service Provider 8",
      city: "Galle",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_4,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Electronic Service Provider 9",
      city: "Badulla",
      desc: "Electrician",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_1,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    
  ];

  export const eventManagementPersons=[
    {
      name: "Event Management worker 1",
      city: "Badulla",
      desc: "Event-coordinator",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_1,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Event Management worker 2",
      city: "Badulla",
      desc: "Event-organizer",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Event Management worker 3",
      city: "Badulla",
      desc: "Event-coordinator",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_3,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Event Management worker 4",
      city: "Badulla",
      desc: "Event-organizer",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_4,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Event Management worker 5",
      city: "Badulla",
      desc: "Event-coordinator",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_1,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Event Management worker 6",
      city: "Badulla",
      desc: "Event-organizer",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Event Management worker 7",
      city: "Badulla",
      desc: "Event-coordinator",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_3,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Event Management worker 8",
      city: "Badulla",
      desc: "Event-organizer",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_4,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Event Management worker 9",
      city: "Badulla",
      desc: "Event-coordinator",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_1,
      email: "lewis@email.com",
      phone: "0769688839",
    },
    {
      name: "Event Management worker 10",
      city: "Badulla",
      desc: "Event-organizer",
      exp: "I have 2 years work experience and done some courses",
      online: false,
      profile: user_2,
      email: "lewis@email.com",
      phone: "0769688839",
    },
  ]